<a href="https://colab.research.google.com/github/PravinV001/Python/blob/main/LINEAR_REGRESSION_MY_TEST_COLAB.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [96]:
!gdown 1RRbLfbAPiihXP50KDQQc6Cr52-r0fsoF  # Original train data

# Clean data is not working so using exact CArs 24 data
#!gdown 1UpLnYA48VylGUMMLG-uQE1gfJe12Lh   # Cleaned data from your paste

Downloading...
From: https://drive.google.com/uc?id=1RRbLfbAPiihXP50KDQQc6Cr52-r0fsoF
To: /content/train-cars24-car-price.csv
100% 1.25M/1.25M [00:00<00:00, 55.8MB/s]

In [97]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
df = pd.read_csv('train-cars24-car-price.csv')
df.head()

,full_name,selling_price,year,seller_type,km_driven,fuel_type,transmission_type,mileage,engine,max_power,seats
0,Maruti SX4 Zxi BSIII,2.85,2007.0,Individual,110000,Petrol,Manual,15.00,1586.0,104.68,5.0
1,Hyundai i20 Sportz 1.4 CRDi,4.70,2012.0,Dealer,70000,Diesel,Manual,21.90,1396.0,88.76,5.0
2,Maruti Swift VDI BSIV,5.25,2015.0,Individual,70000,Diesel,Manual,25.20,1248.0,74.00,5.0
3,Honda City 1.3 EXI,1.25,2005.0,Individual,90000,Petrol,Manual,13.00,1343.0,90.00,5.0
4,Volkswagen Polo 1.2 MPI Comfortline,4.65,2015.0,Dealer,41000,Petrol,Manual,16.47,1198.0,74.00,5.0

## Fixed Linear Regression Model

In [99]:
from sklearn import model_selection
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score, mean_squared_error

import numpy as np
import pandas as pd
df.drop("full_name", axis=1, inplace=True)

print(df.dtypes)
print(df.shape)
#print(df['fuel_type'].unique())
#print(df['seller_type'].unique())
#print(df['transmission_type'].unique())
#print(df['full_name'].unique())
#print(df['full_name'].nunique())

# I am converting Categorical to Numerical using OHE having said that I can verify and clear data more
# for example make comany name differnt than model name. Also, check Null value and replacement accordingly

categorical_cols = ["seller_type","fuel_type","transmission_type"]
df_e= pd.get_dummies(df, columns=categorical_cols, prefix=categorical_cols,drop_first=True)

X=df_e.drop('selling_price',axis=1) # values convert DF to numpy 2 D array (.values)
y=df_e['selling_price']

print(df_e.head(5))
print(df_e.dtypes)

KeyError: "['full_name'] not found in axis"

In [100]:
from sklearn.preprocessing import StandardScaler, MinMaxScaler

#print(X.shape)
#print(y.shape)

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=42)

# Scale the data to get better reults earlier R2 score was 61% only
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train) # this always results in numPy Array
model=LinearRegression()
model.fit(X_train,y_train)

X_test = scaler.transform(X_test)
#print(X_train)

#running Linear model


y_pred=model.predict(X_test)

# Analysing Matrix
r2=r2_score(y_test,y_pred)
mse=mean_squared_error(y_test,y_pred)

print(f'R² Score: {r2:.4f}')
print(f'MSE. : {mse:.4f}')

R² Score: 0.6049
MSE. : 24.7867

In [88]:
# SS calculations (fixes your ANOVA reference)
SS_res = np.sum((y_test - y_pred)**2)
SS_tot = np.sum((y_test - np.mean(y_test))**2)
SS_reg = SS_tot - SS_res
print(f'SS Residual: {SS_res:.4f}')
print(f'SS Regression: {SS_reg:.4f}')
print(f'SS Total: {SS_tot:.4f}')

SS Residual: 69353.0940
SS Regression: 106166.1184
SS Total: 175519.2124

## Model Coefficientsmodel.coef_ shows feature importance.

In [89]:
print('Feature coefficients:', model.coef_)
print('Intercept:', model.intercept_)

Feature coefficients: [ 1.70810344 -0.77325225 -0.05049881  2.04312824  5.02270944 -0.90488013
  0.11497853 -0.07572322 -0.89447515  0.03762265  0.08484546 -1.08536313
 -0.72429443]
Intercept: 7.39276601001084

In [90]:
print(df_e.dtypes)
print("Shape of X_train: ", X_train.shape)

print("Shape of y_train: ", y_train.shape)


print("Shape of X_test: ", X_test.shape)

print("Shape of y_test: ", y_test.shape)

selling_price                   float64
year                            float64
km_driven                         int64
mileage                         float64
engine                          float64
max_power                       float64
seats                           float64
seller_type_Individual             bool
seller_type_Trustmark Dealer       bool
fuel_type_Diesel                   bool
fuel_type_Electric                 bool
fuel_type_LPG                      bool
fuel_type_Petrol                   bool
transmission_type_Manual           bool
dtype: object
Shape of X_train:  (11188, 13)
Shape of y_train:  (11188,)
Shape of X_test:  (2798, 13)
Shape of y_test:  (2798,)

Multicolinarity test on this data

In [91]:
# Stats model work when I have converted Categorical OHE boolean data usinf standard scaling

import statsmodels.api as sm

X_sm = sm.add_constant(X_train)

model = sm.OLS(y_train, X_sm) # OLS ordinary least square = Linear Regression
results = model.fit()

print(results.summary())

print(X_sm)

                            OLS Regression Results
==============================================================================
Dep. Variable:                      y   R-squared:                       0.587
Model:                            OLS   Adj. R-squared:                  0.586
Method:                 Least Squares   F-statistic:                     1219.
Date:                Sun, 19 Apr 2026   Prob (F-statistic):               0.00
Time:                        16:23:23   Log-Likelihood:                -36351.
No. Observations:               11188   AIC:                         7.273e+04
Df Residuals:                   11174   BIC:                         7.283e+04
Df Model:                          13
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          7.3928      0.059    125.335      0.000       7.277       7.508
x1             1.7081      0.070     24.373      0.000       1.571       1.845
x2            -0.7733      0.069    -11.240      0.000      -0.908      -0.638
x3            -0.0505      0.089     -0.567      0.571      -0.225       0.124
x4             2.0431      0.142     14.421      0.000       1.765       2.321
x5             5.0227      0.118     42.718      0.000       4.792       5.253
x6            -0.9049      0.078    -11.587      0.000      -1.058      -0.752
x7             0.1150      0.062      1.866      0.062      -0.006       0.236
x8            -0.0757      0.060     -1.270      0.204      -0.193       0.041
x9            -0.8945      0.233     -3.831      0.000      -1.352      -0.437
x10            0.0376      0.061      0.620      0.535      -0.081       0.157
x11            0.0848      0.065      1.306      0.192      -0.043       0.212
x12           -1.0854      0.237     -4.578      0.000      -1.550      -0.621
x13           -0.7243      0.073     -9.890      0.000      -0.868      -0.581
==============================================================================
Omnibus:                    22731.115   Durbin-Watson:                   2.017
Prob(Omnibus):                  0.000   Jarque-Bera (JB):        220563986.844
Skew:                          16.341   Prob(JB):                         0.00
Kurtosis:                     690.078   Cond. No.                         9.88
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[[ 1.         -0.76387516  0.21163668 ... -0.05760285 -0.98386276
  -2.02641164]
 [ 1.         -0.76387516 -0.06671963 ... -0.05760285 -0.98386276
   0.49348315]
 [ 1.         -1.68200249  0.00286945 ... -0.05760285  1.01640192
   0.49348315]
 ...
 [ 1.         -1.0699176   2.36889814 ... -0.05760285 -0.98386276
   0.49348315]
 [ 1.          1.07237951 -0.99457402 ... -0.05760285 -0.98386276
  -2.02641164]
 [ 1.          0.15425218  0.28122576 ... -0.05760285 -0.98386276
   0.49348315]]

In [106]:
from statsmodels.stats.outliers_influence import variance_inflation_factor

# Get column names from the original features DataFrame before it was scaled
feature_cols = X.columns

# Create a DataFrame using the scaled data and original column names
X_t = pd.DataFrame(X_train, columns=feature_cols)

# Calculate VIF for each feature
vif = pd.DataFrame()
vif["Feature"] = X_t.columns
print(vif)
vif["VIF"] = [variance_inflation_factor(X_t.values, i) for i in range(X_t.shape[1])]
vif['VIF'] = round(vif['VIF'], 2)
vif = vif.sort_values(by = "VIF", ascending = False)
vif

                         Feature
0                           year
1                      km_driven
2                        mileage
3                         engine
4                      max_power
5                          seats
6         seller_type_Individual
7   seller_type_Trustmark Dealer
8               fuel_type_Diesel
9             fuel_type_Electric
10                 fuel_type_LPG
11              fuel_type_Petrol
12      transmission_type_Manual

                         Feature    VIF
11              fuel_type_Petrol  16.15
8               fuel_type_Diesel  15.67
3                         engine   5.77
4                      max_power   3.97
2                        mileage   2.28
5                          seats   1.75
12      transmission_type_Manual   1.54
0                           year   1.41
1                      km_driven   1.36
10                 fuel_type_LPG   1.21
6         seller_type_Individual   1.09
9             fuel_type_Electric   1.06
7   seller_type_Trustmark Dealer   1.02

In [111]:
X_train_new=pd.DataFrame(X_train, columns=feature_cols)
#X_train_new
X_train_new=X_train_new.drop('fuel_type_Petrol',axis=1)
X_train_new

,year,km_driven,mileage,engine,max_power,seats,seller_type_Individual,seller_type_Trustmark Dealer,fuel_type_Diesel,fuel_type_Electric,fuel_type_LPG,transmission_type_Manual
0,-0.763875,0.211637,-0.492746,0.001665,-2.022707,-0.376615,-0.795792,-0.101011,1.02700,-0.02991,-0.057603,-2.026412
1,-0.763875,-0.066720,-1.369191,2.871893,1.549197,2.012030,-0.795792,-0.101011,1.02700,-0.02991,-0.057603,0.493483
2,-1.682002,0.002869,-1.001301,-0.162899,-0.277121,-0.376615,-0.795792,-0.101011,-0.97371,-0.02991,-0.057603,0.493483
3,-0.457833,0.142048,1.400808,0.042979,0.019628,-0.376615,-0.795792,-0.101011,1.02700,-0.02991,-0.057603,0.493483
4,0.460295,0.002869,1.444089,0.042979,0.019628,-0.376615,-0.795792,-0.101011,1.02700,-0.02991,-0.057603,0.493483
...,...,...,...,...,...,...,...,...,...,...,...,...
11183,-0.151790,-0.066720,-1.325910,1.762440,2.559455,-0.376615,-0.795792,-0.101011,1.02700,-0.02991,-0.057603,-2.026412
11184,1.072380,-0.298683,-0.600949,1.949255,0.159275,0.817707,-0.795792,-0.101011,1.02700,-0.02991,-0.057603,0.493483
11185,-1.069918,2.368898,0.145652,-0.145742,-0.648058,-0.376615,1.256610,-0.101011,1.02700,-0.02991,-0.057603,0.493483
11186,1.072380,-0.994574,0.727784,0.990398,1.964646,-0.376615,-0.795792,-0.101011,1.02700,-0.02991,-0.057603,-2.026412
11187,0.154252,0.281226,-1.371355,1.941630,0.050176,2.012030,-0.795792,-0.101011,1.02700,-0.02991,-0.057603,0.493483

In [113]:
# Use the columns directly from X_train_new to avoid NaN columns
X_t = X_train_new.copy()

# Calculate VIF for each feature
vif = pd.DataFrame()
vif["Feature"] = X_t.columns
vif["VIF"] = [variance_inflation_factor(X_t.values, i) for i in range(X_t.shape[1])]
vif['VIF'] = round(vif['VIF'], 2)
vif = vif.sort_values(by = "VIF", ascending = False)
vif

                         Feature   VIF
3                         engine  5.72
4                      max_power  3.97
2                        mileage  2.15
8               fuel_type_Diesel  1.83
5                          seats  1.74
11      transmission_type_Manual  1.54
0                           year  1.41
1                      km_driven  1.36
6         seller_type_Individual  1.09
7   seller_type_Trustmark Dealer  1.02
9             fuel_type_Electric  1.01
10                 fuel_type_LPG  1.01